/* automatically generated by rust-bindgen */

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
pub type ValueType = ::std::os::raw::c_uint;

pub type ostream = [u64; 20usize];
pub type string = [u64; 3usize];
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct pair {
    pub _address: u8,
}
pub type pair_first_type = u8;
pub type pair_second_type = u8;
pub type pair__EnableB = u8;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct pair__CheckArgs {
    pub _address: u8,
}
pub type pair__CheckArgsDep = u8;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct pair__CheckTupleLikeConstructor {
    pub _address: u8,
}
pub type pair__CheckTLC = u8;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct less {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct allocator {
    pub _address: u8,
}
pub type allocator_size_type = u64;
pub type allocator_difference_type = u64;
pub type allocator_pointer = u8;
pub type allocator_const_pointer = u8;
pub type allocator_reference = u8;
pub type allocator_const_reference = u8;
pub type allocator_value_type = u8;
pub type allocator_propagate_on_container_move_assignment = u8;
pub type allocator_is_always_equal = u8;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct allocator_rebind {
    pub _address: u8,
}
pub type allocator_rebind_other = u8;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct default_delete {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct unique_ptr {
    pub _address: u8,
}
pub type unique_ptr_element_type = u8;
pub type unique_ptr_deleter_type = u8;
pub type unique_ptr_pointer = u8;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct unique_ptr___nat {
    pub _address: u8,
}
pub type unique_ptr__DeleterSFINAE = u8;
pub type unique_ptr__LValRefType = u8;
pub type unique_ptr__GoodRValRefType = u8;
pub type unique_ptr__BadRValRefType = u8;
pub type unique_ptr__EnableIfDeleterDefaultConstructible = u8;
pub type unique_ptr__EnableIfDeleterConstructible = u8;
pub type unique_ptr__EnableIfMoveConvertible = u8;
pub type unique_ptr__EnableIfDeleterConvertible = u8;
pub type unique_ptr__EnableIfDeleterAssignable = u8;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct equal_to {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct char_traits {
    pub _address: u8,
}
pub type char_traits_char_type = u8;
pub type char_traits_int_type = u32;
pub type char_traits_off_type = u64;
pub type char_traits_pos_type = u8;
pub type char_traits_state_type = [u64; 16usize];
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct basic_string {
    pub _address: u8,
}
pub type basic_string___self = u8;
pub type basic_string___self_view = u8;
pub type basic_string_traits_type = u8;
pub type basic_string_value_type = u8;
pub type basic_string_allocator_type = u8;
pub type basic_string___alloc_traits = u8;
pub type basic_string_size_type = u8;
pub type basic_string_difference_type = u8;
pub type basic_string_reference = u8;
pub type basic_string_const_reference = u8;
pub type basic_string_pointer = u8;
pub type basic_string_const_pointer = u8;
pub type basic_string_iterator = u8;
pub type basic_string_const_iterator = u8;
pub type basic_string_reverse_iterator = u8;
pub type basic_string_const_reverse_iterator = u8;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct basic_string___long {
    pub _address: u8,
}
pub const basic_string___min_cap: basic_string__bindgen_ty_1 = 0;
pub type basic_string__bindgen_ty_1 = i32;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct basic_string___short {
    pub _address: u8,
}
#[repr(C)]
#[repr(align(1))]
#[derive(Copy, Clone)]
pub union basic_string___short__bindgen_ty_1 {
    pub _bindgen_opaque_blob: u8,
}
impl Default for basic_string___short__bindgen_ty_1 {
    fn default() -> Self {
        unsafe { ::std::mem::zeroed() }
    }
}
#[repr(C)]
#[repr(align(1))]
#[derive(Copy, Clone)]
pub union basic_string___ulx {
    pub _bindgen_opaque_blob: [u8; 0usize],
}
impl Default for basic_string___ulx {
    fn default() -> Self {
        unsafe { ::std::mem::zeroed() }
    }
}
pub const basic_string___n_words: basic_string__bindgen_ty_2 = 0;
pub type basic_string__bindgen_ty_2 = i32;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct basic_string___raw {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct basic_string___rep {
    pub _address: u8,
}
#[repr(C)]
#[repr(align(1))]
#[derive(Copy, Clone)]
pub union basic_string___rep__bindgen_ty_1 {
    pub _bindgen_opaque_blob: [u8; 0usize],
}
impl Default for basic_string___rep__bindgen_ty_1 {
    fn default() -> Self {
        unsafe { ::std::mem::zeroed() }
    }
}
pub const basic_string___alignment: basic_string__bindgen_ty_3 = 0;
pub type basic_string__bindgen_ty_3 = i32;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct map {
    pub _address: u8,
}
pub type map_key_type = u8;
pub type map_mapped_type = u8;
pub type map_value_type = u8;
pub type map_key_compare = u8;
pub type map_allocator_type = u8;
pub type map_reference = u8;
pub type map_const_reference = u8;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct map_value_compare {
    pub _address: u8,
}
pub type map___value_type = u8;
pub type map___vc = u8;
pub type map___allocator_type = u8;
pub type map___base = u8;
pub type map___node_traits = u8;
pub type map___alloc_traits = u8;
pub type map_pointer = u8;
pub type map_const_pointer = u8;
pub type map_size_type = u8;
pub type map_difference_type = u8;
pub type map_iterator = u8;
pub type map_const_iterator = u8;
pub type map_reverse_iterator = u8;
pub type map_const_reverse_iterator = u8;
pub type map___node = u8;
pub type map___node_allocator = u8;
pub type map___node_pointer = u8;
pub type map___node_base_pointer = u8;
pub type map___parent_pointer = u8;
pub type map__Dp = u8;
pub type map___node_holder = u8;
pub type array___self = u8;
pub type array_value_type = u8;
pub type array_reference = u8;
pub type array_const_reference = u8;
pub type array_iterator = u8;
pub type array_const_iterator = u8;
pub type array_pointer = u8;
pub type array_const_pointer = u8;
pub type array_size_type = u64;
pub type array_difference_type = u64;
pub type array_reverse_iterator = u8;
pub type array_const_reverse_iterator = u8;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct vector {
    pub _address: u8,
}
pub type vector___base = u8;
pub type vector___default_allocator_type = u8;
pub type vector___self = u8;
pub type vector_value_type = u8;
pub type vector_allocator_type = u8;
pub type vector___alloc_traits = u8;
pub type vector_reference = u8;
pub type vector_const_reference = u8;
pub type vector_size_type = u8;
pub type vector_difference_type = u8;
pub type vector_pointer = u8;
pub type vector_const_pointer = u8;
pub type vector_iterator = u8;
pub type vector_const_iterator = u8;
pub type vector_reverse_iterator = u8;
pub type vector_const_reverse_iterator = u8;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct vector___RAII_IncreaseAnnotator {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct unordered_map {
    pub _address: u8,
}
pub type unordered_map_key_type = u8;
pub type unordered_map_mapped_type = u8;
pub type unordered_map_hasher = u8;
pub type unordered_map_key_equal = u8;
pub type unordered_map_allocator_type = u8;
pub type unordered_map_value_type = u8;
pub type unordered_map_reference = u8;
pub type unordered_map_const_reference = u8;
pub type unordered_map___value_type = u8;
pub type unordered_map___hasher = u8;
pub type unordered_map___key_equal = u8;
pub type unordered_map___allocator_type = u8;
pub type unordered_map___table = u8;
pub type unordered_map__NodeTypes = u8;
pub type unordered_map___node_pointer = u8;
pub type unordered_map___node_const_pointer = u8;
pub type unordered_map___node_traits = u8;
pub type unordered_map___node_allocator = u8;
pub type unordered_map___node = u8;
pub type unordered_map__Dp = u8;
pub type unordered_map___node_holder = u8;
pub type unordered_map___alloc_traits = u8;
pub type unordered_map_pointer = u8;
pub type unordered_map_const_pointer = u8;
pub type unordered_map_size_type = u8;
pub type unordered_map_difference_type = u8;
pub type unordered_map_iterator = u8;
pub type unordered_map_const_iterator = u8;
pub type unordered_map_local_iterator = u8;
pub type unordered_map_const_local_iterator = u8;
pub type __darwin_size_t = ::std::os::raw::c_ulong;
pub const EncodedGeometryType_INVALID_GEOMETRY_TYPE: EncodedGeometryType = -1;
pub const EncodedGeometryType_POINT_CLOUD: EncodedGeometryType = 0;
pub const EncodedGeometryType_TRIANGULAR_MESH: EncodedGeometryType = 1;
pub type EncodedGeometryType = i32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IndexType<ValueTypeT> {
    pub value_: ValueTypeT,
    pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<ValueTypeT>>,
}
pub type IndexType_ThisIndexType<ValueTypeT> = IndexType<ValueTypeT>;
pub type IndexType_ValueType<ValueTypeT> = ValueTypeT;
impl<ValueTypeT> Default for IndexType<ValueTypeT> {
    fn default() -> Self {
        unsafe { ::std::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct AttributeValueIndex_tag_type_ {
    pub _address: u8,
}
pub type AttributeValueIndex = IndexType<u32>;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct PointIndex_tag_type_ {
    pub _address: u8,
}
pub type PointIndex = IndexType<u32>;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct FaceIndex_tag_type_ {
    pub _address: u8,
}
pub type FaceIndex = IndexType<u32>;
pub const DataType_DT_INVALID: DataType = 0;
pub const DataType_DT_INT8: DataType = 1;
pub const DataType_DT_UINT8: DataType = 2;
pub const DataType_DT_INT16: DataType = 3;
pub const DataType_DT_UINT16: DataType = 4;
pub const DataType_DT_INT32: DataType = 5;
pub const DataType_DT_UINT32: DataType = 6;
pub const DataType_DT_INT64: DataType = 7;
pub const DataType_DT_UINT64: DataType = 8;
pub const DataType_DT_FLOAT32: DataType = 9;
pub const DataType_DT_FLOAT64: DataType = 10;
pub const DataType_DT_BOOL: DataType = 11;
pub const DataType_DT_TYPES_COUNT: DataType = 12;
pub type DataType = u32;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct DataBufferDescriptor {
    pub buffer_id: i64,
    pub buffer_update_count: i64,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct DataBuffer {
    pub data_: [u64; 3usize],
    pub descriptor_: DataBufferDescriptor,
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco10DataBuffer6UpdateEPKvx"]
    pub fn DataBuffer_Update(
        this: *mut DataBuffer,
        data: *const ::std::os::raw::c_void,
        size: i64,
    ) -> bool;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco10DataBuffer6UpdateEPKvxx"]
    pub fn DataBuffer_Update1(
        this: *mut DataBuffer,
        data: *const ::std::os::raw::c_void,
        size: i64,
        offset: i64,
    ) -> bool;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco10DataBuffer6ResizeEx"]
    pub fn DataBuffer_Resize(this: *mut DataBuffer, new_size: i64);
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco10DataBuffer17WriteDataToStreamERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE"]
    pub fn DataBuffer_WriteDataToStream(this: *mut DataBuffer, stream: *mut ostream);
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco10DataBufferC1Ev"]
    pub fn DataBuffer_DataBuffer(this: *mut DataBuffer);
}
impl DataBuffer {
    #[inline]
    pub unsafe fn Update(&mut self, data: *const ::std::os::raw::c_void, size: i64) -> bool {
        DataBuffer_Update(self, data, size)
    }
    #[inline]
    pub unsafe fn Update1(
        &mut self,
        data: *const ::std::os::raw::c_void,
        size: i64,
        offset: i64,
    ) -> bool {
        DataBuffer_Update1(self, data, size, offset)
    }
    #[inline]
    pub unsafe fn Resize(&mut self, new_size: i64) {
        DataBuffer_Resize(self, new_size)
    }
    #[inline]
    pub unsafe fn WriteDataToStream(&mut self, stream: *mut ostream) {
        DataBuffer_WriteDataToStream(self, stream)
    }
    #[inline]
    pub unsafe fn new() -> Self {
        let mut __bindgen_tmp = ::std::mem::uninitialized();
        DataBuffer_DataBuffer(&mut __bindgen_tmp);
        __bindgen_tmp
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GeometryAttribute {
    pub buffer_: *mut DataBuffer,
    pub buffer_descriptor_: DataBufferDescriptor,
    pub num_components_: i8,
    pub data_type_: DataType,
    pub normalized_: bool,
    pub byte_stride_: i64,
    pub byte_offset_: i64,
    pub attribute_type_: GeometryAttribute_Type,
    pub unique_id_: u32,
}
pub const GeometryAttribute_Type_INVALID: GeometryAttribute_Type = -1;
pub const GeometryAttribute_Type_POSITION: GeometryAttribute_Type = 0;
pub const GeometryAttribute_Type_NORMAL: GeometryAttribute_Type = 1;
pub const GeometryAttribute_Type_COLOR: GeometryAttribute_Type = 2;
pub const GeometryAttribute_Type_TEX_COORD: GeometryAttribute_Type = 3;
pub const GeometryAttribute_Type_GENERIC: GeometryAttribute_Type = 4;
pub const GeometryAttribute_Type_NAMED_ATTRIBUTES_COUNT: GeometryAttribute_Type = 5;
pub type GeometryAttribute_Type = i32;
extern "C" {
    #[link_name = "\u{1}__ZN5draco17GeometryAttribute4InitENS0_4TypeEPNS_10DataBufferEaNS_8DataTypeEbxx"]
    pub fn GeometryAttribute_Init(
        this: *mut GeometryAttribute,
        attribute_type: GeometryAttribute_Type,
        buffer: *mut DataBuffer,
        num_components: i8,
        data_type: DataType,
        normalized: bool,
        byte_stride: i64,
        byte_offset: i64,
    );
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco17GeometryAttribute8CopyFromERKS0_"]
    pub fn GeometryAttribute_CopyFrom(
        this: *mut GeometryAttribute,
        src_att: *const GeometryAttribute,
    ) -> bool;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco17GeometryAttribute11ResetBufferEPNS_10DataBufferExx"]
    pub fn GeometryAttribute_ResetBuffer(
        this: *mut GeometryAttribute,
        buffer: *mut DataBuffer,
        byte_stride: i64,
        byte_offset: i64,
    );
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco17GeometryAttributeC1Ev"]
    pub fn GeometryAttribute_GeometryAttribute(this: *mut GeometryAttribute);
}
impl Default for GeometryAttribute {
    fn default() -> Self {
        unsafe { ::std::mem::zeroed() }
    }
}
impl GeometryAttribute {
    #[inline]
    pub unsafe fn Init(
        &mut self,
        attribute_type: GeometryAttribute_Type,
        buffer: *mut DataBuffer,
        num_components: i8,
        data_type: DataType,
        normalized: bool,
        byte_stride: i64,
        byte_offset: i64,
    ) {
        GeometryAttribute_Init(
            self,
            attribute_type,
            buffer,
            num_components,
            data_type,
            normalized,
            byte_stride,
            byte_offset,
        )
    }
    #[inline]
    pub unsafe fn CopyFrom(&mut self, src_att: *const GeometryAttribute) -> bool {
        GeometryAttribute_CopyFrom(self, src_att)
    }
    #[inline]
    pub unsafe fn ResetBuffer(
        &mut self,
        buffer: *mut DataBuffer,
        byte_stride: i64,
        byte_offset: i64,
    ) {
        GeometryAttribute_ResetBuffer(self, buffer, byte_stride, byte_offset)
    }
    #[inline]
    pub unsafe fn new() -> Self {
        let mut __bindgen_tmp = ::std::mem::uninitialized();
        GeometryAttribute_GeometryAttribute(&mut __bindgen_tmp);
        __bindgen_tmp
    }
}
#[repr(C)]
#[derive(Debug, Default)]
pub struct Options {
    pub options_: [u64; 3usize],
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco7Options15MergeAndReplaceERKS0_"]
    pub fn Options_MergeAndReplace(this: *mut Options, other_options: *const Options);
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco7Options6SetIntERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEi"]
    pub fn Options_SetInt(this: *mut Options, name: *const string, val: ::std::os::raw::c_int);
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco7Options8SetFloatERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEf"]
    pub fn Options_SetFloat(this: *mut Options, name: *const string, val: f32);
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco7Options7SetBoolERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEb"]
    pub fn Options_SetBool(this: *mut Options, name: *const string, val: bool);
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco7Options9SetStringERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9_"]
    pub fn Options_SetString(this: *mut Options, name: *const string, val: *const string);
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco7Options6GetIntERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE"]
    pub fn Options_GetInt(this: *const Options, name: *const string) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco7Options6GetIntERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEi"]
    pub fn Options_GetInt1(
        this: *const Options,
        name: *const string,
        default_val: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco7Options8GetFloatERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE"]
    pub fn Options_GetFloat(this: *const Options, name: *const string) -> f32;
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco7Options8GetFloatERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEf"]
    pub fn Options_GetFloat1(this: *const Options, name: *const string, default_val: f32) -> f32;
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco7Options7GetBoolERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE"]
    pub fn Options_GetBool(this: *const Options, name: *const string) -> bool;
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco7Options7GetBoolERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEb"]
    pub fn Options_GetBool1(this: *const Options, name: *const string, default_val: bool) -> bool;
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco7Options9GetStringERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE"]
    pub fn Options_GetString(this: *const Options, name: *const string) -> string;
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco7Options9GetStringERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9_"]
    pub fn Options_GetString1(
        this: *const Options,
        name: *const string,
        default_val: *const string,
    ) -> string;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco7OptionsC1Ev"]
    pub fn Options_Options(this: *mut Options);
}
impl Options {
    #[inline]
    pub unsafe fn MergeAndReplace(&mut self, other_options: *const Options) {
        Options_MergeAndReplace(self, other_options)
    }
    #[inline]
    pub unsafe fn SetInt(&mut self, name: *const string, val: ::std::os::raw::c_int) {
        Options_SetInt(self, name, val)
    }
    #[inline]
    pub unsafe fn SetFloat(&mut self, name: *const string, val: f32) {
        Options_SetFloat(self, name, val)
    }
    #[inline]
    pub unsafe fn SetBool(&mut self, name: *const string, val: bool) {
        Options_SetBool(self, name, val)
    }
    #[inline]
    pub unsafe fn SetString(&mut self, name: *const string, val: *const string) {
        Options_SetString(self, name, val)
    }
    #[inline]
    pub unsafe fn GetInt(&self, name: *const string) -> ::std::os::raw::c_int {
        Options_GetInt(self, name)
    }
    #[inline]
    pub unsafe fn GetInt1(
        &self,
        name: *const string,
        default_val: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int {
        Options_GetInt1(self, name, default_val)
    }
    #[inline]
    pub unsafe fn GetFloat(&self, name: *const string) -> f32 {
        Options_GetFloat(self, name)
    }
    #[inline]
    pub unsafe fn GetFloat1(&self, name: *const string, default_val: f32) -> f32 {
        Options_GetFloat1(self, name, default_val)
    }
    #[inline]
    pub unsafe fn GetBool(&self, name: *const string) -> bool {
        Options_GetBool(self, name)
    }
    #[inline]
    pub unsafe fn GetBool1(&self, name: *const string, default_val: bool) -> bool {
        Options_GetBool1(self, name, default_val)
    }
    #[inline]
    pub unsafe fn GetString(&self, name: *const string) -> string {
        Options_GetString(self, name)
    }
    #[inline]
    pub unsafe fn GetString1(&self, name: *const string, default_val: *const string) -> string {
        Options_GetString1(self, name, default_val)
    }
    #[inline]
    pub unsafe fn new() -> Self {
        let mut __bindgen_tmp = ::std::mem::uninitialized();
        Options_Options(&mut __bindgen_tmp);
        __bindgen_tmp
    }
}
#[repr(C)]
#[derive(Debug, Default)]
pub struct DracoOptions {
    pub global_options_: Options,
    pub attribute_options_: u8,
}
pub type DracoOptions_AttributeKey<AttributeKeyT> = AttributeKeyT;
pub type DecoderOptions = DracoOptions;
#[repr(C)]
#[derive(Debug)]
pub struct DecoderBuffer {
    pub data_: *const ::std::os::raw::c_char,
    pub data_size_: i64,
    pub pos_: i64,
    pub bit_decoder_: DecoderBuffer_BitDecoder,
    pub bit_mode_: bool,
    pub bitstream_version_: u16,
}
#[repr(C)]
#[derive(Debug)]
pub struct DecoderBuffer_BitDecoder {
    pub bit_buffer_: *const u8,
    pub bit_buffer_end_: *const u8,
    pub bit_offset_: usize,
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco13DecoderBuffer10BitDecoderC1Ev"]
    pub fn DecoderBuffer_BitDecoder_BitDecoder(this: *mut DecoderBuffer_BitDecoder);
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco13DecoderBuffer10BitDecoderD1Ev"]
    pub fn DecoderBuffer_BitDecoder_BitDecoder_destructor(this: *mut DecoderBuffer_BitDecoder);
}
impl Default for DecoderBuffer_BitDecoder {
    fn default() -> Self {
        unsafe { ::std::mem::zeroed() }
    }
}
impl DecoderBuffer_BitDecoder {
    #[inline]
    pub unsafe fn new() -> Self {
        let mut __bindgen_tmp = ::std::mem::uninitialized();
        DecoderBuffer_BitDecoder_BitDecoder(&mut __bindgen_tmp);
        __bindgen_tmp
    }
    #[inline]
    pub unsafe fn destruct(&mut self) {
        DecoderBuffer_BitDecoder_BitDecoder_destructor(self)
    }
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco13DecoderBuffer4InitEPKcm"]
    pub fn DecoderBuffer_Init(
        this: *mut DecoderBuffer,
        data: *const ::std::os::raw::c_char,
        data_size: usize,
    );
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco13DecoderBuffer4InitEPKcmt"]
    pub fn DecoderBuffer_Init1(
        this: *mut DecoderBuffer,
        data: *const ::std::os::raw::c_char,
        data_size: usize,
        version: u16,
    );
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco13DecoderBuffer16StartBitDecodingEbPy"]
    pub fn DecoderBuffer_StartBitDecoding(
        this: *mut DecoderBuffer,
        decode_size: bool,
        out_size: *mut u64,
    ) -> bool;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco13DecoderBuffer14EndBitDecodingEv"]
    pub fn DecoderBuffer_EndBitDecoding(this: *mut DecoderBuffer);
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco13DecoderBufferC1Ev"]
    pub fn DecoderBuffer_DecoderBuffer(this: *mut DecoderBuffer);
}
impl Default for DecoderBuffer {
    fn default() -> Self {
        unsafe { ::std::mem::zeroed() }
    }
}
impl DecoderBuffer {
    #[inline]
    pub unsafe fn Init(&mut self, data: *const ::std::os::raw::c_char, data_size: usize) {
        DecoderBuffer_Init(self, data, data_size)
    }
    #[inline]
    pub unsafe fn Init1(
        &mut self,
        data: *const ::std::os::raw::c_char,
        data_size: usize,
        version: u16,
    ) {
        DecoderBuffer_Init1(self, data, data_size, version)
    }
    #[inline]
    pub unsafe fn StartBitDecoding(&mut self, decode_size: bool, out_size: *mut u64) -> bool {
        DecoderBuffer_StartBitDecoding(self, decode_size, out_size)
    }
    #[inline]
    pub unsafe fn EndBitDecoding(&mut self) {
        DecoderBuffer_EndBitDecoding(self)
    }
    #[inline]
    pub unsafe fn new() -> Self {
        let mut __bindgen_tmp = ::std::mem::uninitialized();
        DecoderBuffer_DecoderBuffer(&mut __bindgen_tmp);
        __bindgen_tmp
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Status {
    pub code_: Status_Code,
    pub error_msg_: string,
}
pub const Status_Code_OK: Status_Code = 0;
pub const Status_Code_DRACO_ERROR: Status_Code = -1;
pub const Status_Code_IO_ERROR: Status_Code = -2;
pub const Status_Code_INVALID_PARAMETER: Status_Code = -3;
pub const Status_Code_UNSUPPORTED_VERSION: Status_Code = -4;
pub const Status_Code_UNKNOWN_VERSION: Status_Code = -5;
pub type Status_Code = i32;
impl Default for Status {
    fn default() -> Self {
        unsafe { ::std::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct StatusOr<T> {
    pub status_: Status,
    pub value_: T,
    pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<T>>,
}
impl<T> Default for StatusOr<T> {
    fn default() -> Self {
        unsafe { ::std::mem::zeroed() }
    }
}
pub const AttributeTransformType_ATTRIBUTE_INVALID_TRANSFORM: AttributeTransformType = -1;
pub const AttributeTransformType_ATTRIBUTE_NO_TRANSFORM: AttributeTransformType = 0;
pub const AttributeTransformType_ATTRIBUTE_QUANTIZATION_TRANSFORM: AttributeTransformType = 1;
pub const AttributeTransformType_ATTRIBUTE_OCTAHEDRON_TRANSFORM: AttributeTransformType = 2;
pub type AttributeTransformType = i32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AttributeTransformData {
    pub transform_type_: AttributeTransformType,
    pub buffer_: DataBuffer,
}
impl Default for AttributeTransformData {
    fn default() -> Self {
        unsafe { ::std::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct IndexTypeVector {
    pub vector_: u8,
}
pub type IndexTypeVector_const_reference = u8;
pub type IndexTypeVector_reference = u8;
#[repr(C)]
pub struct PointAttribute {
    pub _base: GeometryAttribute,
    pub attribute_buffer_: u64,
    pub indices_map_: IndexTypeVector,
    pub num_unique_entries_: ValueType,
    pub identity_mapping_: bool,
    pub attribute_transform_data_: u64,
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco14PointAttribute8CopyFromERKS0_"]
    pub fn PointAttribute_CopyFrom(this: *mut PointAttribute, src_att: *const PointAttribute);
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco14PointAttribute5ResetEm"]
    pub fn PointAttribute_Reset(this: *mut PointAttribute, num_attribute_values: usize) -> bool;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco14PointAttribute17DeduplicateValuesERKNS_17GeometryAttributeE"]
    pub fn PointAttribute_DeduplicateValues(
        this: *mut PointAttribute,
        in_att: *const GeometryAttribute,
    ) -> ValueType;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco14PointAttribute17DeduplicateValuesERKNS_17GeometryAttributeENS_9IndexTypeIjNS_29AttributeValueIndex_tag_type_EEE"]
    pub fn PointAttribute_DeduplicateValues1(
        this: *mut PointAttribute,
        in_att: *const GeometryAttribute,
        in_att_offset: AttributeValueIndex,
    ) -> ValueType;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco14PointAttributeC1Ev"]
    pub fn PointAttribute_PointAttribute(this: *mut PointAttribute);
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco14PointAttributeC1ERKNS_17GeometryAttributeE"]
    pub fn PointAttribute_PointAttribute1(this: *mut PointAttribute, att: *const GeometryAttribute);
}
impl Default for PointAttribute {
    fn default() -> Self {
        unsafe { ::std::mem::zeroed() }
    }
}
impl PointAttribute {
    #[inline]
    pub unsafe fn CopyFrom(&mut self, src_att: *const PointAttribute) {
        PointAttribute_CopyFrom(self, src_att)
    }
    #[inline]
    pub unsafe fn Reset(&mut self, num_attribute_values: usize) -> bool {
        PointAttribute_Reset(self, num_attribute_values)
    }
    #[inline]
    pub unsafe fn DeduplicateValues(&mut self, in_att: *const GeometryAttribute) -> ValueType {
        PointAttribute_DeduplicateValues(self, in_att)
    }
    #[inline]
    pub unsafe fn DeduplicateValues1(
        &mut self,
        in_att: *const GeometryAttribute,
        in_att_offset: AttributeValueIndex,
    ) -> ValueType {
        PointAttribute_DeduplicateValues1(self, in_att, in_att_offset)
    }
    #[inline]
    pub unsafe fn new() -> Self {
        let mut __bindgen_tmp = ::std::mem::uninitialized();
        PointAttribute_PointAttribute(&mut __bindgen_tmp);
        __bindgen_tmp
    }
    #[inline]
    pub unsafe fn new1(att: *const GeometryAttribute) -> Self {
        let mut __bindgen_tmp = ::std::mem::uninitialized();
        PointAttribute_PointAttribute1(&mut __bindgen_tmp, att);
        __bindgen_tmp
    }
}
pub type VectorD_Scalar<ScalarT> = ScalarT;
pub type VectorD_Self = u8;
pub type VectorD_CoefficientType<ScalarT> = ScalarT;
pub type Vector3f = [u32; 3usize];
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct BoundingBox {
    pub min_point_: Vector3f,
    pub max_point_: Vector3f,
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco11BoundingBoxC1ERKNS_7VectorDIfLi3EEES4_"]
    pub fn BoundingBox_BoundingBox(
        this: *mut BoundingBox,
        min_point_in: *const Vector3f,
        max_point_in: *const Vector3f,
    );
}
impl BoundingBox {
    #[inline]
    pub unsafe fn new(min_point_in: *const Vector3f, max_point_in: *const Vector3f) -> Self {
        let mut __bindgen_tmp = ::std::mem::uninitialized();
        BoundingBox_BoundingBox(&mut __bindgen_tmp, min_point_in, max_point_in);
        __bindgen_tmp
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct EntryValue {
    pub data_: [u64; 3usize],
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco10EntryValueC1ERKS0_"]
    pub fn EntryValue_EntryValue(this: *mut EntryValue, value: *const EntryValue);
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco10EntryValueC1ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE"]
    pub fn EntryValue_EntryValue1(this: *mut EntryValue, value: *const string);
}
impl EntryValue {
    #[inline]
    pub unsafe fn new(value: *const EntryValue) -> Self {
        let mut __bindgen_tmp = ::std::mem::uninitialized();
        EntryValue_EntryValue(&mut __bindgen_tmp, value);
        __bindgen_tmp
    }
    #[inline]
    pub unsafe fn new1(value: *const string) -> Self {
        let mut __bindgen_tmp = ::std::mem::uninitialized();
        EntryValue_EntryValue1(&mut __bindgen_tmp, value);
        __bindgen_tmp
    }
}
#[repr(C)]
#[derive(Debug, Default)]
pub struct Metadata {
    pub entries_: [u64; 5usize],
    pub sub_metadatas_: [u64; 5usize],
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco8Metadata11AddEntryIntERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEi"]
    pub fn Metadata_AddEntryInt(this: *mut Metadata, name: *const string, value: i32);
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco8Metadata11GetEntryIntERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPi"]
    pub fn Metadata_GetEntryInt(
        this: *const Metadata,
        name: *const string,
        value: *mut i32,
    ) -> bool;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco8Metadata16AddEntryIntArrayERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKNS1_6vectorIiNS5_IiEEEE"]
    pub fn Metadata_AddEntryIntArray(
        this: *mut Metadata,
        name: *const string,
        value: *const [u64; 3usize],
    );
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco8Metadata16GetEntryIntArrayERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPNS1_6vectorIiNS5_IiEEEE"]
    pub fn Metadata_GetEntryIntArray(
        this: *const Metadata,
        name: *const string,
        value: *mut [u64; 3usize],
    ) -> bool;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco8Metadata14AddEntryDoubleERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEd"]
    pub fn Metadata_AddEntryDouble(this: *mut Metadata, name: *const string, value: f64);
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco8Metadata14GetEntryDoubleERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPd"]
    pub fn Metadata_GetEntryDouble(
        this: *const Metadata,
        name: *const string,
        value: *mut f64,
    ) -> bool;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco8Metadata19AddEntryDoubleArrayERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKNS1_6vectorIdNS5_IdEEEE"]
    pub fn Metadata_AddEntryDoubleArray(this: *mut Metadata, name: *const string, value: *const u8);
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco8Metadata19GetEntryDoubleArrayERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPNS1_6vectorIdNS5_IdEEEE"]
    pub fn Metadata_GetEntryDoubleArray(
        this: *const Metadata,
        name: *const string,
        value: *mut u8,
    ) -> bool;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco8Metadata14AddEntryStringERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9_"]
    pub fn Metadata_AddEntryString(this: *mut Metadata, name: *const string, value: *const string);
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco8Metadata14GetEntryStringERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPS7_"]
    pub fn Metadata_GetEntryString(
        this: *const Metadata,
        name: *const string,
        value: *mut string,
    ) -> bool;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco8Metadata14AddEntryBinaryERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKNS1_6vectorIhNS5_IhEEEE"]
    pub fn Metadata_AddEntryBinary(
        this: *mut Metadata,
        name: *const string,
        value: *const [u64; 3usize],
    );
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco8Metadata14GetEntryBinaryERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPNS1_6vectorIhNS5_IhEEEE"]
    pub fn Metadata_GetEntryBinary(
        this: *const Metadata,
        name: *const string,
        value: *mut [u64; 3usize],
    ) -> bool;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco8Metadata14AddSubMetadataERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS1_10unique_ptrIS0_NS1_14default_deleteIS0_EEEE"]
    pub fn Metadata_AddSubMetadata(
        this: *mut Metadata,
        name: *const string,
        sub_metadata: u64,
    ) -> bool;
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco8Metadata14GetSubMetadataERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE"]
    pub fn Metadata_GetSubMetadata(this: *const Metadata, name: *const string) -> *const Metadata;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco8Metadata11RemoveEntryERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE"]
    pub fn Metadata_RemoveEntry(this: *mut Metadata, name: *const string);
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco8MetadataC1ERKS0_"]
    pub fn Metadata_Metadata(this: *mut Metadata, metadata: *const Metadata);
}
impl Metadata {
    #[inline]
    pub unsafe fn AddEntryInt(&mut self, name: *const string, value: i32) {
        Metadata_AddEntryInt(self, name, value)
    }
    #[inline]
    pub unsafe fn GetEntryInt(&self, name: *const string, value: *mut i32) -> bool {
        Metadata_GetEntryInt(self, name, value)
    }
    #[inline]
    pub unsafe fn AddEntryIntArray(&mut self, name: *const string, value: *const [u64; 3usize]) {
        Metadata_AddEntryIntArray(self, name, value)
    }
    #[inline]
    pub unsafe fn GetEntryIntArray(&self, name: *const string, value: *mut [u64; 3usize]) -> bool {
        Metadata_GetEntryIntArray(self, name, value)
    }
    #[inline]
    pub unsafe fn AddEntryDouble(&mut self, name: *const string, value: f64) {
        Metadata_AddEntryDouble(self, name, value)
    }
    #[inline]
    pub unsafe fn GetEntryDouble(&self, name: *const string, value: *mut f64) -> bool {
        Metadata_GetEntryDouble(self, name, value)
    }
    #[inline]
    pub unsafe fn AddEntryDoubleArray(&mut self, name: *const string, value: *const u8) {
        Metadata_AddEntryDoubleArray(self, name, value)
    }
    #[inline]
    pub unsafe fn GetEntryDoubleArray(&self, name: *const string, value: *mut u8) -> bool {
        Metadata_GetEntryDoubleArray(self, name, value)
    }
    #[inline]
    pub unsafe fn AddEntryString(&mut self, name: *const string, value: *const string) {
        Metadata_AddEntryString(self, name, value)
    }
    #[inline]
    pub unsafe fn GetEntryString(&self, name: *const string, value: *mut string) -> bool {
        Metadata_GetEntryString(self, name, value)
    }
    #[inline]
    pub unsafe fn AddEntryBinary(&mut self, name: *const string, value: *const [u64; 3usize]) {
        Metadata_AddEntryBinary(self, name, value)
    }
    #[inline]
    pub unsafe fn GetEntryBinary(&self, name: *const string, value: *mut [u64; 3usize]) -> bool {
        Metadata_GetEntryBinary(self, name, value)
    }
    #[inline]
    pub unsafe fn AddSubMetadata(&mut self, name: *const string, sub_metadata: u64) -> bool {
        Metadata_AddSubMetadata(self, name, sub_metadata)
    }
    #[inline]
    pub unsafe fn GetSubMetadata(&self, name: *const string) -> *const Metadata {
        Metadata_GetSubMetadata(self, name)
    }
    #[inline]
    pub unsafe fn RemoveEntry(&mut self, name: *const string) {
        Metadata_RemoveEntry(self, name)
    }
    #[inline]
    pub unsafe fn new(metadata: *const Metadata) -> Self {
        let mut __bindgen_tmp = ::std::mem::uninitialized();
        Metadata_Metadata(&mut __bindgen_tmp, metadata);
        __bindgen_tmp
    }
}
#[repr(C)]
#[derive(Debug, Default)]
pub struct AttributeMetadata {
    pub _base: Metadata,
    pub att_unique_id_: u32,
}
#[repr(C)]
#[derive(Debug, Default)]
pub struct GeometryMetadata {
    pub _base: Metadata,
    pub att_metadatas_: [u64; 3usize],
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco16GeometryMetadata33GetAttributeMetadataByStringEntryERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9_"]
    pub fn GeometryMetadata_GetAttributeMetadataByStringEntry(
        this: *const GeometryMetadata,
        entry_name: *const string,
        entry_value: *const string,
    ) -> *const AttributeMetadata;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco16GeometryMetadata20AddAttributeMetadataENSt3__110unique_ptrINS_17AttributeMetadataENS1_14default_deleteIS3_EEEE"]
    pub fn GeometryMetadata_AddAttributeMetadata(
        this: *mut GeometryMetadata,
        att_metadata: u64,
    ) -> bool;
}
impl GeometryMetadata {
    #[inline]
    pub unsafe fn GetAttributeMetadataByStringEntry(
        &self,
        entry_name: *const string,
        entry_value: *const string,
    ) -> *const AttributeMetadata {
        GeometryMetadata_GetAttributeMetadataByStringEntry(self, entry_name, entry_value)
    }
    #[inline]
    pub unsafe fn AddAttributeMetadata(&mut self, att_metadata: u64) -> bool {
        GeometryMetadata_AddAttributeMetadata(self, att_metadata)
    }
}
#[repr(C)]
pub struct PointCloud__bindgen_vtable(::std::os::raw::c_void);
#[repr(C)]
pub struct PointCloud {
    pub vtable_: *const PointCloud__bindgen_vtable,
    pub metadata_: u64,
    pub attributes_: [u64; 3usize],
    pub named_attribute_index_: [u64; 15usize],
    pub num_points_: ValueType,
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco10PointCloud18NumNamedAttributesENS_17GeometryAttribute4TypeE"]
    pub fn PointCloud_NumNamedAttributes(
        this: *const PointCloud,
        type_: GeometryAttribute_Type,
    ) -> i32;
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco10PointCloud19GetNamedAttributeIdENS_17GeometryAttribute4TypeE"]
    pub fn PointCloud_GetNamedAttributeId(
        this: *const PointCloud,
        type_: GeometryAttribute_Type,
    ) -> i32;
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco10PointCloud19GetNamedAttributeIdENS_17GeometryAttribute4TypeEi"]
    pub fn PointCloud_GetNamedAttributeId1(
        this: *const PointCloud,
        type_: GeometryAttribute_Type,
        i: ::std::os::raw::c_int,
    ) -> i32;
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco10PointCloud17GetNamedAttributeENS_17GeometryAttribute4TypeE"]
    pub fn PointCloud_GetNamedAttribute(
        this: *const PointCloud,
        type_: GeometryAttribute_Type,
    ) -> *const PointAttribute;
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco10PointCloud17GetNamedAttributeENS_17GeometryAttribute4TypeEi"]
    pub fn PointCloud_GetNamedAttribute1(
        this: *const PointCloud,
        type_: GeometryAttribute_Type,
        i: ::std::os::raw::c_int,
    ) -> *const PointAttribute;
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco10PointCloud27GetNamedAttributeByUniqueIdENS_17GeometryAttribute4TypeEj"]
    pub fn PointCloud_GetNamedAttributeByUniqueId(
        this: *const PointCloud,
        type_: GeometryAttribute_Type,
        id: u32,
    ) -> *const PointAttribute;
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco10PointCloud22GetAttributeByUniqueIdEj"]
    pub fn PointCloud_GetAttributeByUniqueId(
        this: *const PointCloud,
        id: u32,
    ) -> *const PointAttribute;
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco10PointCloud24GetAttributeIdByUniqueIdEj"]
    pub fn PointCloud_GetAttributeIdByUniqueId(this: *const PointCloud, unique_id: u32) -> i32;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco10PointCloud12AddAttributeENSt3__110unique_ptrINS_14PointAttributeENS1_14default_deleteIS3_EEEE"]
    pub fn PointCloud_AddAttribute(this: *mut PointCloud, pa: u64) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco10PointCloud12AddAttributeERKNS_17GeometryAttributeEbj"]
    pub fn PointCloud_AddAttribute1(
        this: *mut PointCloud,
        att: *const GeometryAttribute,
        identity_mapping: bool,
        num_attribute_values: ValueType,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco10PointCloud15CreateAttributeERKNS_17GeometryAttributeEbj"]
    pub fn PointCloud_CreateAttribute(
        this: *const PointCloud,
        att: *const GeometryAttribute,
        identity_mapping: bool,
        num_attribute_values: ValueType,
    ) -> u64;
}
extern "C" {
    #[link_name = "\u{1}__ZNK5draco10PointCloud18ComputeBoundingBoxEv"]
    pub fn PointCloud_ComputeBoundingBox(this: *const PointCloud) -> BoundingBox;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco10PointCloudC1Ev"]
    pub fn PointCloud_PointCloud(this: *mut PointCloud);
}
impl Default for PointCloud {
    fn default() -> Self {
        unsafe { ::std::mem::zeroed() }
    }
}
impl PointCloud {
    #[inline]
    pub unsafe fn NumNamedAttributes(&self, type_: GeometryAttribute_Type) -> i32 {
        PointCloud_NumNamedAttributes(self, type_)
    }
    #[inline]
    pub unsafe fn GetNamedAttributeId(&self, type_: GeometryAttribute_Type) -> i32 {
        PointCloud_GetNamedAttributeId(self, type_)
    }
    #[inline]
    pub unsafe fn GetNamedAttributeId1(
        &self,
        type_: GeometryAttribute_Type,
        i: ::std::os::raw::c_int,
    ) -> i32 {
        PointCloud_GetNamedAttributeId1(self, type_, i)
    }
    #[inline]
    pub unsafe fn GetNamedAttribute(&self, type_: GeometryAttribute_Type) -> *const PointAttribute {
        PointCloud_GetNamedAttribute(self, type_)
    }
    #[inline]
    pub unsafe fn GetNamedAttribute1(
        &self,
        type_: GeometryAttribute_Type,
        i: ::std::os::raw::c_int,
    ) -> *const PointAttribute {
        PointCloud_GetNamedAttribute1(self, type_, i)
    }
    #[inline]
    pub unsafe fn GetNamedAttributeByUniqueId(
        &self,
        type_: GeometryAttribute_Type,
        id: u32,
    ) -> *const PointAttribute {
        PointCloud_GetNamedAttributeByUniqueId(self, type_, id)
    }
    #[inline]
    pub unsafe fn GetAttributeByUniqueId(&self, id: u32) -> *const PointAttribute {
        PointCloud_GetAttributeByUniqueId(self, id)
    }
    #[inline]
    pub unsafe fn GetAttributeIdByUniqueId(&self, unique_id: u32) -> i32 {
        PointCloud_GetAttributeIdByUniqueId(self, unique_id)
    }
    #[inline]
    pub unsafe fn AddAttribute(&mut self, pa: u64) -> ::std::os::raw::c_int {
        PointCloud_AddAttribute(self, pa)
    }
    #[inline]
    pub unsafe fn AddAttribute1(
        &mut self,
        att: *const GeometryAttribute,
        identity_mapping: bool,
        num_attribute_values: ValueType,
    ) -> ::std::os::raw::c_int {
        PointCloud_AddAttribute1(self, att, identity_mapping, num_attribute_values)
    }
    #[inline]
    pub unsafe fn CreateAttribute(
        &self,
        att: *const GeometryAttribute,
        identity_mapping: bool,
        num_attribute_values: ValueType,
    ) -> u64 {
        PointCloud_CreateAttribute(self, att, identity_mapping, num_attribute_values)
    }
    #[inline]
    pub unsafe fn ComputeBoundingBox(&self) -> BoundingBox {
        PointCloud_ComputeBoundingBox(self)
    }
    #[inline]
    pub unsafe fn new() -> Self {
        let mut __bindgen_tmp = ::std::mem::uninitialized();
        PointCloud_PointCloud(&mut __bindgen_tmp);
        __bindgen_tmp
    }
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco10PointCloud12SetAttributeEiNSt3__110unique_ptrINS_14PointAttributeENS1_14default_deleteIS3_EEEE"]
    pub fn PointCloud_SetAttribute(
        this: *mut ::std::os::raw::c_void,
        att_id: ::std::os::raw::c_int,
        pa: u64,
    );
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco10PointCloud15DeleteAttributeEi"]
    pub fn PointCloud_DeleteAttribute(
        this: *mut ::std::os::raw::c_void,
        att_id: ::std::os::raw::c_int,
    );
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco10PointCloud26DeduplicateAttributeValuesEv"]
    pub fn PointCloud_DeduplicateAttributeValues(this: *mut ::std::os::raw::c_void) -> bool;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco10PointCloud19DeduplicatePointIdsEv"]
    pub fn PointCloud_DeduplicatePointIds(this: *mut ::std::os::raw::c_void);
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco10PointCloud25ApplyPointIdDeduplicationERKNS_15IndexTypeVectorINS_9IndexTypeIjNS_20PointIndex_tag_type_EEES4_EERKNSt3__16vectorIS4_NS8_9allocatorIS4_EEEE"]
    pub fn PointCloud_ApplyPointIdDeduplication(
        this: *mut ::std::os::raw::c_void,
        id_map: *const IndexTypeVector,
        unique_point_ids: *const u8,
    );
}
pub const MeshAttributeElementType_MESH_VERTEX_ATTRIBUTE: MeshAttributeElementType = 0;
pub const MeshAttributeElementType_MESH_CORNER_ATTRIBUTE: MeshAttributeElementType = 1;
pub const MeshAttributeElementType_MESH_FACE_ATTRIBUTE: MeshAttributeElementType = 2;
pub type MeshAttributeElementType = u32;
#[repr(C)]
pub struct Mesh {
    pub _base: PointCloud,
    pub attribute_data_: [u64; 3usize],
    pub faces_: IndexTypeVector,
}
pub type Mesh_Face = [u32; 3usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Mesh_AttributeData {
    pub element_type: MeshAttributeElementType,
}
impl Default for Mesh_AttributeData {
    fn default() -> Self {
        unsafe { ::std::mem::zeroed() }
    }
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco4MeshC1Ev"]
    pub fn Mesh_Mesh(this: *mut Mesh);
}
impl Default for Mesh {
    fn default() -> Self {
        unsafe { ::std::mem::zeroed() }
    }
}
impl Mesh {
    #[inline]
    pub unsafe fn new() -> Self {
        let mut __bindgen_tmp = ::std::mem::uninitialized();
        Mesh_Mesh(&mut __bindgen_tmp);
        __bindgen_tmp
    }
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco4Mesh25ApplyPointIdDeduplicationERKNS_15IndexTypeVectorINS_9IndexTypeIjNS_20PointIndex_tag_type_EEES4_EERKNSt3__16vectorIS4_NS8_9allocatorIS4_EEEE"]
    pub fn Mesh_ApplyPointIdDeduplication(
        this: *mut ::std::os::raw::c_void,
        id_map: *const IndexTypeVector,
        unique_point_ids: *const u8,
    );
}
#[repr(C)]
#[derive(Debug)]
pub struct Decoder {
    pub options_: DecoderOptions,
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco7Decoder22GetEncodedGeometryTypeEPNS_13DecoderBufferE"]
    pub fn Decoder_GetEncodedGeometryType(
        in_buffer: *mut DecoderBuffer,
    ) -> StatusOr<EncodedGeometryType>;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco7Decoder26DecodePointCloudFromBufferEPNS_13DecoderBufferE"]
    pub fn Decoder_DecodePointCloudFromBuffer(
        this: *mut Decoder,
        in_buffer: *mut DecoderBuffer,
    ) -> u8;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco7Decoder20DecodeMeshFromBufferEPNS_13DecoderBufferE"]
    pub fn Decoder_DecodeMeshFromBuffer(this: *mut Decoder, in_buffer: *mut DecoderBuffer) -> u8;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco7Decoder22DecodeBufferToGeometryEPNS_13DecoderBufferEPNS_10PointCloudE"]
    pub fn Decoder_DecodeBufferToGeometry(
        this: *mut Decoder,
        in_buffer: *mut DecoderBuffer,
        out_geometry: *mut PointCloud,
    ) -> Status;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco7Decoder22DecodeBufferToGeometryEPNS_13DecoderBufferEPNS_4MeshE"]
    pub fn Decoder_DecodeBufferToGeometry1(
        this: *mut Decoder,
        in_buffer: *mut DecoderBuffer,
        out_geometry: *mut Mesh,
    ) -> Status;
}
extern "C" {
    #[link_name = "\u{1}__ZN5draco7Decoder25SetSkipAttributeTransformENS_17GeometryAttribute4TypeE"]
    pub fn Decoder_SetSkipAttributeTransform(this: *mut Decoder, att_type: GeometryAttribute_Type);
}
impl Default for Decoder {
    fn default() -> Self {
        unsafe { ::std::mem::zeroed() }
    }
}
impl Decoder {
    #[inline]
    pub unsafe fn GetEncodedGeometryType(
        in_buffer: *mut DecoderBuffer,
    ) -> StatusOr<EncodedGeometryType> {
        Decoder_GetEncodedGeometryType(in_buffer)
    }
    #[inline]
    pub unsafe fn DecodePointCloudFromBuffer(&mut self, in_buffer: *mut DecoderBuffer) -> u8 {
        Decoder_DecodePointCloudFromBuffer(self, in_buffer)
    }
    #[inline]
    pub unsafe fn DecodeMeshFromBuffer(&mut self, in_buffer: *mut DecoderBuffer) -> u8 {
        Decoder_DecodeMeshFromBuffer(self, in_buffer)
    }
    #[inline]
    pub unsafe fn DecodeBufferToGeometry(
        &mut self,
        in_buffer: *mut DecoderBuffer,
        out_geometry: *mut PointCloud,
    ) -> Status {
        Decoder_DecodeBufferToGeometry(self, in_buffer, out_geometry)
    }
    #[inline]
    pub unsafe fn DecodeBufferToGeometry1(
        &mut self,
        in_buffer: *mut DecoderBuffer,
        out_geometry: *mut Mesh,
    ) -> Status {
        Decoder_DecodeBufferToGeometry1(self, in_buffer, out_geometry)
    }
    #[inline]
    pub unsafe fn SetSkipAttributeTransform(&mut self, att_type: GeometryAttribute_Type) {
        Decoder_SetSkipAttributeTransform(self, att_type)
    }
}
